progres_search/urls.py
from django.urls import path

from . import views

app_name = "progres_search"
urlpatterns = [
    path("", views.index, name="index"),
    path("results/<str:submission_url_str>", views.results, name="results"),
]

progres_server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("progres_search.urls")),
    path("admin/", admin.site.urls),
]

progres_search/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
import progres as pg

class Submission(models.Model):
    targetdbs   = [(x, x) for x in pg.pre_embedded_dbs_faiss + pg.pre_embedded_dbs]
    fileformats = [(x, x) for x in ["guess", "pdb", "mmcif", "mmtf"]]

    url_str = models.CharField(max_length=20)
    job_name = models.CharField(
        max_length=200,
        blank=True,
        help_text="Give the job a name (optional).",
    )
    n_res_total = models.IntegerField()
    res_ranges = models.CharField(max_length=200)
    dom_pdbs = models.JSONField()
    embeddings = models.JSONField()
    targetdb = models.CharField(
        max_length=20,
        choices=targetdbs,
        default="afted",
        verbose_name="Target database",
        help_text=("Choose a database to search against. afted is the "
                   "<a href='https://www.science.org/doi/10.1126/science.adq4946'>"
                   "TED domains</a> from the <a href='https://alphafold.ebi.ac.uk'>AlphaFold "
                   "database</a>. bfvd is domains from the <a href='https://bfvd.foldseek.com'>"
                   "Big Fantastic Virus Database (BFVD)</a>. scope95/scope40/cath40/ecod70 "
                   "are domains from classifications of the PDB. pdb100 is the whole PDB split "
                   "into domains with Chainsaw. af21org is domains from the "
                   "AlphaFold set of 21 model organisms. See "
                   "<a href='https://github.com/greener-group/progres#available-databases'>"
                   "here</a> for more info."),
    )
    chainsaw = models.BooleanField(
        default=False,
        verbose_name="Split domains",
        help_text=("Whether to split the query structure into domains with "
                   "<a href='https://doi.org/10.1093/bioinformatics/btae296'>Chainsaw</a> and "
                   "search with each domain separately. Recommended for structures above "
                   "200-300 residues. Note that whether or not this option is selected, only "
                   "the first chain in the file is considered."),
    )
    minsimilarity = models.FloatField(
        default=0.8,
        validators=[MinValueValidator(0.0), MaxValueValidator(1.0)],
        verbose_name="Minimum similarity",
        help_text=("The Progres score above which to return hits. The default of 0.8 indicates "
                   "the same fold. Must be 0 -> 1."),
    )
    maxhits = models.IntegerField(
        default=100,
        validators=[MinValueValidator(1), MaxValueValidator(1000)],
        verbose_name="Max number of hits",
        help_text=("The maximum number of hits per domain to return. Hits will only be returned "
                   "if they are above the minimum score given above. Must be 1 -> 1000."),
    )
    fileformat = models.CharField(
        max_length=20,
        choices=fileformats,
        default="guess",
        verbose_name="File format",
        help_text=("By default the format of the uploaded file is guessed from the file "
                   "extension, but it can be set explicitly here. Supported formats are "
                   "PDB, mmCIF and MMTF."),
    )
    submission_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.job_name

progres_search/forms.py
from django import forms
from django.core.validators import ValidationError

from .models import Submission

def file_size_validator(value):
    limit = 10 * 1024 * 1024
    if value.size > limit:
        raise ValidationError("File too large. Size should not exceed 10 MiB.")

class SubmitJobForm(forms.ModelForm):
    file = forms.FileField(validators=[file_size_validator])

    class Meta:
        model = Submission
        fields = ["job_name", "targetdb", "chainsaw", "minsimilarity", "maxhits", "fileformat"]

progres_search/views.py
from Bio.PDB.MMCIFParser import MMCIFParser
from Bio.PDB.mmtf import MMTFParser
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
import faiss
import progres as pg
import torch
from torch_geometric.loader import DataLoader
import importlib.metadata
import os
from random import choices
import string
from tempfile import NamedTemporaryFile

from .models import Submission
from .forms import SubmitJobForm

base_url = "progres.mrc-lmb.cam.ac.uk"
example_url_str = "ABC123"
device = "cpu"

print("Loading Progres data, this will take a minute")

data_dir = os.path.join(os.path.dirname(__file__), "data")

pg_model = pg.load_trained_model(device)
target_data_dict = {}
for targetdb in pg.pre_embedded_dbs:
    fp = os.path.join(pg.database_dir, targetdb + ".pt")
    target_data_dict[targetdb] = torch.load(fp, map_location=device)
target_index_dict = {}
for targetdb in pg.pre_embedded_dbs_faiss:
    fp = os.path.join(pg.database_dir, targetdb + "_noembs.pt")
    target_data_dict[targetdb] = torch.load(fp, map_location=device)
    fp = os.path.join(pg.database_dir, f"{targetdb}.index")
    target_index_dict[targetdb] = faiss.read_index(fp)

scope_data = {}
with open(os.path.join(data_dir, "dir.des.scope.2.08-stable.txt")) as f:
    for line in f.readlines():
        if not line.startswith("#"):
            cols = line.split()
            if cols[1] == "px":
                dom_id, pdb_id, res_range_scope = cols[3], cols[4], cols[5]
                if res_range_scope != "-":
                    chain_id = res_range_scope.split(":")[0]
                    if res_range_scope.endswith(":"):
                        res_range = "*:" + chain_id
                    else:
                        res_ranges = [rr.split(":")[1] for rr in res_range_scope.split(",")]
                        res_range = "_".join(res_ranges) + ":" + chain_id
                    scope_data[dom_id] = [res_range, pdb_id]

cath_data = {}
with open(os.path.join(data_dir, "cath-b-newest-all")) as f:
    for line in f.readlines():
        cols = line.split()
        dom_id, res_range_cath = cols[0], cols[3]
        res_ranges = [rr.split(":")[0] for rr in res_range_cath.split(",")]
        chain_id = res_range_cath.split(":")[-1]
        res_range = "_".join(res_ranges) + ":" + chain_id
        cath_data[dom_id] = res_range

ecod_data = {}
with open(os.path.join(data_dir, "ecod.latest.F70.domains.txt")) as f:
    for line in f.readlines():
        if not line.startswith("#"):
            cols = line.split()
            dom_id, pdb_id, res_range_ecod = cols[1], cols[4], cols[6]
            res_ranges = [rr.split(":")[1] for rr in res_range_ecod.split(",")]
            chain_id = res_range_ecod.split(":")[0]
            res_range = "_".join(res_ranges) + ":" + chain_id
            ecod_data[dom_id] = [res_range, pdb_id]

print("Loaded Progres data")

backbone_atoms = ["N", "CA", "C", "O"]

def read_pdb_coords(line):
    return [float(line[30:38]), float(line[38:46]), float(line[46:54])]

def read_ca_backbone(fp, fileformat="guess", res_ranges="all"):
    chosen_format = pg.get_file_format(fp, fileformat)
    if res_ranges == "all":
        n_domains = 1
    else:
        domains_res = []
        for res_range in res_ranges.split(","):
            domain_res = []
            for rr in res_range.split("_"):
                domain_res.extend(pg.extract_res_range(rr))
            domains_res.append(set(domain_res))
            n_domains = len(domains_res)

    dom_coords_ca, dom_pdbs = [[] for _ in range(n_domains)], ["" for _ in range(n_domains)]
    n_res_total = 0

    if chosen_format == "pdb":
        with open(fp) as f:
            chain_id = None
            for line in f.readlines():
                if line.startswith("ATOM  "):
                    if chain_id is None:
                        chain_id = line[21]
                    elif line[21] != chain_id:
                        break # Only read first chain
                    resnum = int(line[22:26])
                    atom_name = line[12:16].strip()
                    if atom_name == "CA":
                        n_res_total += 1
                        for di in range(n_domains):
                            if res_ranges == "all" or resnum in domains_res[di]:
                                dom_coords_ca[di].append(read_pdb_coords(line))
                                break
                    for di in range(n_domains):
                        if res_ranges == "all" or resnum in domains_res[di]:
                            dom_pdbs[di] += line
                            break
                elif line.startswith("ENDMDL"):
                    break
    elif chosen_format == "mmcif" or chosen_format == "mmtf":
        if chosen_format == "mmcif":
            parser = MMCIFParser()
            struc = parser.get_structure("", fp)
        else:
            struc = MMTFParser.get_structure(fp)
        for model in struc:
            for chain in model:
                chain_id = chain.get_id()[0] # Restrict chain ID to be one character
                for res in chain:
                    if res.get_id()[0] == " ": # Ignore hetero atoms
                        resnum, ins_code = res.get_id()[1], res.get_id()[2]
                        resname = res.get_resname()
                        for a in res:
                            if a.get_name() == "CA":
                                n_res_total += 1
                                for di in range(n_domains):
                                    if res_ranges == "all" or resnum in domains_res[di]:
                                        x, y, z = a.get_coord()
                                        dom_coords_ca[di].append([float(x), float(y), float(z)])
                                        break
                            for di in range(n_domains):
                                if res_ranges == "all" or resnum in domains_res[di]:
                                    x, y, z = a.get_coord()
                                    pdb_line = f"ATOM  {a.get_serial_number():>5} {a.get_fullname():4}{a.get_altloc():1}{resname:3} {chain_id:1}{resnum:>4}{ins_code:1}   {x:8.3f}{y:8.3f}{z:8.3f}{a.get_occupancy():6.2f}{a.get_bfactor():6.2f}              \n"
                                    dom_pdbs[di] += pdb_line
                                    break
                break # Only read first chain
            break # Only read first model
    else:
        raise ValueError("fileformat must be \"guess\", \"pdb\", \"mmcif\" or \"mmtf\"")
    return dom_coords_ca, dom_pdbs, n_res_total

def generate_url_str():
    done = False
    while not done:
        trial_url_str = "".join(choices(string.ascii_uppercase + string.digits, k=6))
        if len(Submission.objects.filter(url_str=trial_url_str)) == 0:
            done = True
    return trial_url_str

def index(request):
    if request.method == "POST":
        form = SubmitJobForm(request.POST, request.FILES)
        if form.is_valid():
            fileformat = form.cleaned_data["fileformat"]
            chainsaw = form.cleaned_data["chainsaw"]
            # Keep the file name ending to allow the file format to be guessed
            try:
                temp_file = NamedTemporaryFile(suffix=("." + request.FILES["file"].name))
                with open(temp_file.name, "wb+") as destination:
                    for chunk in request.FILES["file"].chunks():
                        destination.write(chunk)
            except:
                error_text = "Error uploading file. Maybe try again later."
                return render(request, "progres_search/error.html", {"error_text": error_text})
            if chainsaw:
                try:
                    res_ranges = pg.predict_domains(
                        temp_file.name,
                        pg.get_file_format(temp_file.name, fileformat),
                        device,
                    )
                except:
                    error_text = ("Error running Chainsaw. Check your uploaded file and make "
                                  "sure that it contains protein residues and that the correct "
                                  "file format is selected during upload.")
                    return render(request, "progres_search/error.html", {"error_text": error_text})
                if res_ranges is None:
                    error_text = ("Chainsaw did not find any domains in your uploaded protein "
                                  "structure. Try running without splitting into domains.")
                    return render(request, "progres_search/error.html", {"error_text": error_text})
            else:
                res_ranges = "all"
            try:
                dom_coords_ca, dom_pdbs, n_res_total = read_ca_backbone(temp_file.name,
                                                                        fileformat, res_ranges)
            except:
                error_text = ("Error reading structure file. Check your uploaded file and make "
                              "sure the correct file format is selected during upload.")
                return render(request, "progres_search/error.html", {"error_text": error_text})
            temp_file.close()
            embeddings = [pg.embed_coords(c, model=pg_model, device=device).tolist()
                          for c in dom_coords_ca]
            url_str = generate_url_str()
            submission = Submission(
                url_str=url_str,
                job_name=form.cleaned_data["job_name"],
                n_res_total=n_res_total,
                res_ranges=res_ranges,
                dom_pdbs=dom_pdbs,
                embeddings=embeddings,
                targetdb=form.cleaned_data["targetdb"],
                fileformat=fileformat,
                minsimilarity=form.cleaned_data["minsimilarity"],
                maxhits=form.cleaned_data["maxhits"],

progres_search/templates/progres_search/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-LFK0R6SQ83"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-LFK0R6SQ83');
    </script>

    <meta charset="utf-8"/>
    <link rel="icon" href="https://raw.githubusercontent.com/jgreener64/jgreener64.github.io/master/_assets/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>

    <style>
        #content {
            padding-left: 10px;
        }
        .text_block {
            max-width: 800px;
        }
        #submission_table {
            max-width: 1200px;
        }
        #results_left {
            width: 65%;
            float: left;
            padding-right: 20px;
        }
        #results_right {
            width: 35%;
            float: left;
            position: fixed;
            top: 0px;
            right: 0px;
            padding-top: 10px;
        }
        .results_table {
            background-color: rgb(234, 250, 250);
        }
        #viewer_query {
            position: relative;
            height: 250px;
            width: 300px;
        }
        #viewer_target {
            position: relative;
            height: 250px;
            width: 300px;
        }
    </style>
</head>

<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

progres_search/templates/progres_search/error.html
{% extends "progres_search/base.html" %}

{% block title %}Progres error{% endblock %}

{% block content %}

<h1>
    Progres error
</h1>

<div class="text_block">
    <p>
        {{ error_text }}
    <p>
</div>

<hr>

{% endblock %}

progres_search/templates/progres_search/index.html
{% extends "progres_search/base.html" %}

{% block title %}Progres server{% endblock %}

{% block content %}

<h1>
    Progres server
</h1>

<div class="text_block">
    <p>
        Progres lets you quickly search protein structures against pre-embedded structural databases.
        This can be useful for remote homology detection, protein classification and inferring function from structure.
    <p>
    </p>
        Due to the way it is trained, Progres works with protein domains rather than whole structures. However, queries can be automatically split into domains before searching.
    <p>
    </p>
        If you want to search with many structures or embed databases to search against, please use the <a href="https://github.com/greener-group/progres">Progres software</a>.
        If you use the Progres web server or software, please cite the paper:
    </p>

    <ul>
        <li>
            Greener JG and Jamali K, Fast protein structure searching using structure graph embeddings, <em>Bioinformatics Advances</em> 5:1, vbaf042 (2025) - <a href="https://academic.oup.com/bioinformaticsadvances/article/5/1/vbaf042/8107707">link</a>
        </li>
    </ul>
</div>

<hr>

<h2>
    Submit:
</h2>

<div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table id="submission_table" class="table">
            {% for field in form %}
                <tr>
                    <th>{{ field.label_tag }}</th>
                    <td>{{ field }} {{ field.errors }}</td>
                    <td>{{ field.help_text|safe }}</td>
                </tr>
            {% endfor %}
        </table>
        {{ form.non_field_errors }}
        <input type="submit" value="Submit">
    </form>
</div>

<div class="text_block">
    <p>
        Or view an <a href="{% url 'progres_search:results' example_url_str %}">example results page</a>.
    </p>

    <p>
        If you find an issue with the web server, please <a href="https://github.com/greener-group/progres_server/issues">open an issue</a> or <a href="https://www2.mrc-lmb.cam.ac.uk/groups/greener">get in touch</a>.
    </p>
</div>

{% endblock %}

progres_search/templates/progres_search/results.html
{% extends "progres_search/base.html" %}

{% block title %}Progres results{% endblock %}

{% block content %}

<link rel="stylesheet" href="https://cdn.datatables.net/2.1.3/css/dataTables.dataTables.css" />
<script src="https://3Dmol.org/build/3Dmol-min.js"></script>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.datatables.net/2.1.3/js/dataTables.js"></script>

<a href="{% url 'progres_search:index' %}">
    Home
</a>

<h1>
    Progres results
</h1>

<div id="results_left">
    <ul>
        <li>Job name: {{ submission.job_name }}</li>
        <li>URL: <a href="https://{{ base_url }}/results/{{ submission.url_str }}">{{ base_url }}/results/{{ submission.url_str }}</a></li>
        <li>Query size: {{ submission.n_res_total }} residues</li>
        <li>
            n domains: {{ n_domains }} ( jump to
                {% for i in domains_iter %}
                    <a href="#domain_{{ i }}">{{ i }}</a>{% if not forloop.last %} / {% endif %}
                {% endfor %}
            )
        </li>
        <li>Database: {{ submission.targetdb }}</li>
        <li>
            Parameters: minsimilarity {{ submission.minsimilarity }},
            maxhits {{ submission.maxhits }}, chainsaw {{ chainsaw_str }},
            faiss {{ faiss_str }}, progres v{{ progres_version }}
        </li>
    </ul>

    <hr>

    {% for domain_n, domain_size, domain_res_range, results in domains_zip %}
        <h3 id="domain_{{ domain_n }}">
            Domain {{ domain_n }}
        </h3>

        <a href="#">
            Go to top
        </a>
        |
        <a href="javascript:void(0);" onclick="download_tsv_file({{ domain_n }})">
            Download table as TSV file
        </a>

        <ul>
            <li>
                Domain size: {{ domain_size }} residues ({{ domain_res_range }})
            </li>
        </ul>

        <table id="table_{{ domain_n }}" class="results_table">
            <thead>
                <tr>
                    <th>Hit n</th>
                    <th>Domain</th>
                    <th>Hit nres</th>
                    <th>Similarity</th>
                    <th>Notes</th>
                    <th>View</th>
                </tr>
            </thead>
            <tbody>
                {% for domain, hit_nres, similarity, note, url, target_res_range in results %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ domain }}</td>
                        <td>{{ hit_nres }}</td>
                        <td>{{ similarity|floatformat:4 }}</td>
                        <td>{{ note }}</td>
                        <td>
                            <button onclick="view_structure('{{ url }}', '{{ target_res_range }}', {{ domain_n }}, {{ forloop.counter }});">
                                View
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <hr>
    {% endfor %}
</div>

<div id="results_right">
    <h3 id="query_info">
        Query domain
    </h3>

    <div id="viewer_query"></div>

    <h3>
        Selected hit domain
    </h3>

    <div id="viewer_target"></div>

    <ul>
        <li>Hit n: <span id="hit_info_n"></span></li>
        <li>Download URL: <span id="hit_info_url"></span></li>
        <li>Residue range: <span id="hit_info_res"></span></li>
    </ul>
</div>

<script>
    function view_structure(url, target_res_range, domain_n, hit_n) {
        let element_query = $("#viewer_query");
        let element_target = $("#viewer_target");
        let config = {backgroundColor: "white"};
        let ss_colours = { h: 0xff0000, s: 0xffff00, c: 0x00ff00 }
        let viewer_query = $3Dmol.createViewer(element_query, config);
        let viewer_target = $3Dmol.createViewer(element_target, config);
        let query_dom_pdbs = [
            {% for query_dom_pdb in query_dom_pdbs %}
                `{{ query_dom_pdb }}`,
            {% endfor %}
        ];
        let res_range_list = target_res_range.split(":")[0].split("_");
        let chain_id = target_res_range.split(":")[1];

        jQuery.ajax(url, {
            success: function(target_pdb) {
                viewer_query.addModel(query_dom_pdbs[domain_n - 1], "pdb");
                viewer_query.setStyle({}, {cartoon: {colorscheme: {prop:"ss", map:ss_colours}}});
                viewer_query.zoomTo();
                viewer_query.render();

                viewer_target.addModel(target_pdb, "pdb");
                viewer_target.setStyle({}, {cartoon: {color: "grey", opacity: 0.7}});
                for (var i = 0; i < res_range_list.length; i++) {
                    viewer_target.setStyle(
                        res_range_list[i] == "*" ? {chain: chain_id} :
                                                   {chain: chain_id, resi: res_range_list[i]},
                        {cartoon: {colorscheme: {prop:"ss", map:ss_colours}}},
                    );
                }
                viewer_target.zoomTo();
                viewer_target.render();
                $("#query_info").html("Query domain " + domain_n)
                $("#hit_info_n").html(hit_n)
                $("#hit_info_url").html("<a href='" + url + "'>" + url + "</a>")
                $("#hit_info_res").html(target_res_range)
            },
            error: function(hdr, status, err) {
                console.error("Failed to load PDB " + url + ": " + err);
            },
        });
    };

    // See https://www.geeksforgeeks.org/how-to-export-html-table-to-csv-using-javascript
    function download_tsv_file(domain_n) {
        domain_results_tsv = [
            {% for tsv_string in tsv_strings %}
                "{{ tsv_string }}",
            {% endfor %}
        ];
        tsv_file = new Blob([domain_results_tsv[domain_n-1]], { type: "text/tab-separated-values" });
        let temp_link = document.createElement("a");
        temp_link.download = "progres_result_dom_" + domain_n + ".tsv";
        let url = window.URL.createObjectURL(tsv_file);
        temp_link.href = url;
        temp_link.style.display = "none";
        document.body.appendChild(temp_link);
        temp_link.click();
        document.body.removeChild(temp_link);
    };

    $(document).ready( function () {
        {% for i in domains_iter %}
            $("#table_{{ i }}").DataTable();
        {% endfor %}
        view_structure('{{ url_start }}', '{{ res_range_start }}', 1, 1);
    });
</script>

{% endblock %}